services:
  flaskapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_con_volumen
    ports:
      - "8080:8080"
    environment:
      VAR2: Mundo variable
    # 👇 Esta línea enlaza tu código local al contenedor directamente
    volumes:
      - ./warp:/dagster_home         
    working_dir: /dagster_home
    command: python prueba.py