#TODO: Es dev dado que el volumen se enlaza al directorio local

services:
  flaskapp:
    build:
      context: .
      dockerfile: docker/Dockerfile.sin_enlace
    container_name: disk_sin_enlace
    ports:
      - "8080:8080"
    environment:
      VAR2: Mundo variable
    working_dir: /dagster_home        # ✅ Contenedor se posiciona aquí
    command: python prueba.py         # ✅ Ejecuta el archivo